name: Build
on:
  workflow_dispatch:
      inputs:
        package_name:
          description: "Package name of the game:"
          required: true
          default: "com.dts.freefireth"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Make gradlew executable
      run: chmod +x gradlew
      
    - name: Update module.gradle
      run: |
        sed -i 's/moduleDescription = "/moduleDescription = "(${{ github.event.inputs.package_name }}) /g' module.gradle || true
        
    - name: Update game.h
      run: |
        mkdir -p module/src/main/cpp
        sed -i "s/com.game.packagename/${{ github.event.inputs.package_name }}/g" module/src/main/cpp/game.h || true
        echo '#define GamePackageName "'${{ github.event.inputs.package_name }}'"' > module/src/main/cpp/game.h
        
    - name: Build with Gradle
      run: ./gradlew :module:assembleRelease --no-daemon
      
    - name: Find and Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: zygisk-il2cppdumper-${{ github.event.inputs.package_name }}
        path: |
          module/build/outputs/apk/release/*.zip
          out/*.zip
          **/*.zip
